services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NUXT_PUBLIC_API_URL=http://host.docker.internal:8080
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=http://host.docker.internal:8080